Rename SHIELD's vault process to "shield-vault"
To avoid naming conflicts in monit:

    Error: service name conflict, vault already defined
    '/var/vcap/sys/run/targets/vault.pid'